WITH plugins_daily as (
 
 SELECT 
 CASE
 WHEN TYPE = 12010 THEN 'PAYMENT'
 WHEN TYPE = 12020 THEN 'ACCOUNTING'
 WHEN TYPE = 12030 THEN 'PAYMENT'
 WHEN TYPE = 12040 THEN 'GATE2SHOP'
 WHEN TYPE = 12050 THEN 'PAYMENT'
 WHEN TYPE = 12060 THEN 'ECOMM'
 WHEN TYPE = 12070 THEN 'ACCOUNTING'
 WHEN TYPE = 12080 THEN 'MISC'
 WHEN TYPE = 12090 THEN 'ECOMM'
 WHEN TYPE = 12100 THEN 'PAYMENT'
 WHEN TYPE = 12120 THEN 'PAYMENT'
 WHEN TYPE = 12130 THEN 'PAYMENT'
 WHEN TYPE = 12140 THEN 'ECOMM'
 WHEN TYPE = 12150 THEN 'MISC'
 WHEN TYPE = 12160 THEN 'PAYMENT'
 WHEN TYPE = 12170 THEN 'PAYMENT'
 WHEN TYPE = 12180 THEN 'ECOMM'
 END Pgroup,
 CASE
 WHEN TYPE = 12010 THEN 'PAYPAL'
 WHEN TYPE = 12020 THEN 'HASHAVSHEVET'
 WHEN TYPE = 12030 THEN 'BLUESNAP'
 WHEN TYPE = 12040 THEN 'GATE2SHOP'
 WHEN TYPE = 12050 THEN 'PAYONEER'
 WHEN TYPE = 12060 THEN 'WIX'
 WHEN TYPE = 12070 THEN 'PRIORITY'
 WHEN TYPE = 12080 THEN 'RESPONDER'
 WHEN TYPE = 12090 THEN 'SHOPIFY'
 WHEN TYPE = 12100 THEN 'CARDCOM'
 WHEN TYPE = 12120 THEN 'MAX'
 WHEN TYPE = 12130 THEN 'MESHULAM'
 WHEN TYPE = 12140 THEN 'ETSY'
 WHEN TYPE = 12150 THEN 'GOOGLEDRIVE'
 WHEN TYPE = 12160 THEN 'VCHECK'
 WHEN TYPE = 12170 THEN 'ISRACARD'
 WHEN TYPE = 12180 THEN 'WOOCOMMERCE'
 END Pname,
 COUNT(CASE WHEN CREATION_DATE = '@TMY' THEN p.ID END) CREATED_TM,
 COUNT(CASE WHEN ACTIVATION_DATE = '@TMY' THEN p.ID END) ACTIVATED_TM,
 COUNT(CASE WHEN ACTIVATION_DATE IS NULL THEN p.ID END) WAITING_TM,
 COUNT(CASE WHEN CREATION_DATE <= '@TMY' AND REMOVAL_DATE IS NULL AND ACTIVATION_DATE <= '@TMY' THEN p.ID END) CNT_ACTIVE,
 COUNT(CASE  WHEN REMOVAL_DATE = '@TMY' THEN p.ID END) REMOVED_TM,
 COUNT(CASE  WHEN REMOVAL_DATE = '@TMY' and CREATION_DATE = '@TMY' THEN p.ID END) ADDED_REMOVED_TM,
 avg(diff) avg_diff,
 COUNT(CASE WHEN CREATION_DATE = DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m') THEN p.ID END) CREATED_LM,
 COUNT(CASE WHEN ACTIVATION_DATE = DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m') THEN p.ID END) ACTIVATED_LM,
 COUNT(CASE WHEN CREATION_DATE <= DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m') AND (REMOVAL_DATE IS NULL or REMOVAL_DATE>DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m')) AND ACTIVATION_DATE <= DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m') THEN p.ID END) ACTIVE_LM,
 COUNT(CASE WHEN REMOVAL_DATE = DATE_FORMAT(date_add('month', -1,date '@TMD1'), '%Y-%m') THEN p.ID END) REMOVED_LM
FROM
 (SELECT 
 ID,
 TYPE,
 DATE_FORMAT(REMOVAL_DATE, '%Y-%m') REMOVAL_DATE,
 DATE_FORMAT(CREATION_DATE, '%Y-%m') CREATION_DATE,
 DATE_FORMAT(ACTIVATION_DATE, '%Y-%m') ACTIVATION_DATE,
 DATE_DIFF('day',CREATION_DATE,ACTIVATION_DATE) diff
 FROM
 plugins) p
GROUP BY 1 , 2

)
select '@TMD1' ReportDate, CREATED_TM Val, concat('PLUGIN_',Pgroup,'_',Pname,'_CREATED_TM') DataId from plugins_daily
UNION
select '@TMD1' ReportDate, ACTIVATED_TM,concat('PLUGIN_',Pgroup,'_',Pname,'_ACTIVATED_TM') from plugins_daily
UNION
select '@TMD1' ReportDate, WAITING_TM,  concat('PLUGIN_',Pgroup,'_',Pname,'_WAITING_TM') from plugins_daily
UNION
select '@TMD1' ReportDate, CNT_ACTIVE,  concat('PLUGIN_',Pgroup,'_',Pname,'_CNT_ACTIVE') from plugins_daily
UNION
select '@TMD1' ReportDate, REMOVED_TM,  concat('PLUGIN_',Pgroup,'_',Pname,'_REMOVED_TM') from plugins_daily
UNION
select '@TMD1' ReportDate, avg_diff,   concat('PLUGIN_',Pgroup,'_',Pname,'_AVG_WAIT') from plugins_daily
UNION
select '@TMD1' ReportDate, ADDED_REMOVED_TM, concat('PLUGIN_',Pgroup,'_',Pname,'_ADD_RMV') from plugins_daily
UNION
select '@TMD1' ReportDate, ACTIVATED_LM,concat('PLUGIN_',Pgroup,'_',Pname,'_ACTIVATED_LM') from plugins_daily
UNION
select '@TMD1' ReportDate, ACTIVE_LM,   concat('PLUGIN_',Pgroup,'_',Pname,'_ACTV_LM') from plugins_daily
UNION
select '@TMD1' ReportDate, REMOVED_LM,  concat('PLUGIN_',Pgroup,'_',Pname,'_RMV_LM') from plugins_daily


union 
select
'@TMD1' ReportDate,val Val, 
CONCAT( case WHEN TYPE = 12010 THEN 'PAYPAL'
 WHEN TYPE = 12020 THEN 'HASHAVSHEVET'
 WHEN TYPE = 12030 THEN 'BLUESNAP'
 WHEN TYPE = 12040 THEN 'GATE2SHOP'
 WHEN TYPE = 12050 THEN 'PAYONEER'
 WHEN TYPE = 12060 THEN 'WIX'
 WHEN TYPE = 12070 THEN 'PRIORITY'
 WHEN TYPE = 12080 THEN 'RESPONDER'
 WHEN TYPE = 12090 THEN 'SHOPIFY'
 WHEN TYPE = 12100 THEN 'CARDCOM'
 WHEN TYPE = 12120 THEN 'MAX'
 WHEN TYPE = 12130 THEN 'MESHULAM'
 WHEN TYPE = 12140 THEN 'ETSY'
 WHEN TYPE = 12150 THEN 'GOOGLEDRIVE'
 WHEN TYPE = 12160 THEN 'VCHECK'
 WHEN TYPE = 12170 THEN 'ISRACARD'
 WHEN TYPE = 12180 THEN 'WOOCOMMERCE' end, '_MEDIAN_WAIT_TIME') DataId
from (
select 
TYPE, approx_percentile(DATE_DIFF('day',CREATION_DATE,coalesce(d.ACTIVATION_DATE,NOW())), 0.5) val
-- DATE_DIFF('day',coalesce(d.ACTIVATION_DATE,NOW()),CREATION_DATE) wait_time 
FROM plugins d
WHERE d.CREATION_DATE>=date '@TMD1'
  and d.CREATION_DATE<=date_add('day', -1, date_add('month', 1,date '@TMD1'))
group by 1

  ) a

;

