WITH plugins_daily as (
 
 SELECT 
 CASE
 WHEN TYPE = 12010 THEN 'PAYMENT'
 WHEN TYPE = 12020 THEN 'ACCOUNTING'
 WHEN TYPE = 12030 THEN 'PAYMENT'
 WHEN TYPE = 12040 THEN 'GATE2SHOP'
 WHEN TYPE = 12050 THEN 'PAYMENT'
 WHEN TYPE = 12060 THEN 'ECOMM'
 WHEN TYPE = 12070 THEN 'ACCOUNTING'
 WHEN TYPE = 12080 THEN 'MISC'
 WHEN TYPE = 12090 THEN 'ECOMM'
 WHEN TYPE = 12100 THEN 'PAYMENT'
 WHEN TYPE = 12120 THEN 'PAYMENT'
 WHEN TYPE = 12130 THEN 'PAYMENT'
 WHEN TYPE = 12140 THEN 'ECOMM'
 WHEN TYPE = 12150 THEN 'MISC'
 WHEN TYPE = 12160 THEN 'PAYMENT'
 WHEN TYPE = 12170 THEN 'PAYMENT'
 WHEN TYPE = 12180 THEN 'ECOMM'
 END Pgroup,
 CASE
 WHEN TYPE = 12010 THEN 'PAYPAL'
 WHEN TYPE = 12020 THEN 'HASHAVSHEVET'
 WHEN TYPE = 12030 THEN 'BLUESNAP'
 WHEN TYPE = 12040 THEN 'GATE2SHOP'
 WHEN TYPE = 12050 THEN 'PAYONEER'
 WHEN TYPE = 12060 THEN 'WIX'
 WHEN TYPE = 12070 THEN 'PRIORITY'
 WHEN TYPE = 12080 THEN 'RESPONDER'
 WHEN TYPE = 12090 THEN 'SHOPIFY'
 WHEN TYPE = 12100 THEN 'CARDCOM'
 WHEN TYPE = 12120 THEN 'MAX'
 WHEN TYPE = 12130 THEN 'MESHULAM'
 WHEN TYPE = 12140 THEN 'ETSY'
 WHEN TYPE = 12150 THEN 'GOOGLEDRIVE'
 WHEN TYPE = 12160 THEN 'VCHECK'
 WHEN TYPE = 12170 THEN 'ISRACARD'
 WHEN TYPE = 12180 THEN 'WOOCOMMERCE'
 END Pname,
 COUNT(CASE
 WHEN CREATION_DATE = '@YDAY' THEN p.ID
 END) CREATED_YDAY,
 COUNT(CASE
 WHEN ACTIVATION_DATE = '@YDAY' THEN p.ID
 END) ACTIVATED_YDAY,
 COUNT(CASE
 WHEN
 ACTIVATION_DATE IS NULL
 THEN
 p.ID
 END) WAITING_YDAY,
 COUNT(CASE
 WHEN
 CREATION_DATE < '@YDAY'
 AND REMOVAL_DATE IS NULL
 AND ACTIVATION_DATE < '@YDAY'
 THEN
 p.ID
 END) CNT_ACTIVE,
 COUNT(CASE
 WHEN
 is_active=1
 THEN
 p.ID
 END) CNT_CLR_ACTIVE,
 COUNT(CASE
 WHEN REMOVAL_DATE = '@YDAY' THEN p.ID
 END) REMOVED_YDAY
FROM
 (SELECT 
 p.ID,
 p.TYPE,
 DATE_FORMAT(p.REMOVAL_DATE, '%Y-%m-%d') REMOVAL_DATE,
 DATE_FORMAT(p.CREATION_DATE, '%Y-%m-%d') CREATION_DATE,
 DATE_FORMAT(p.ACTIVATION_DATE, '%Y-%m-%d') ACTIVATION_DATE,
 case when date(abc.date_interval) = date(date_format(now(), '%Y-%m-01')) then 1 else 0 end is_active
 FROM
 prod.PLUGINS p 
 left join 
    (
        select product_key, max(date_interval) date_interval from 
        prod.account_billing_charges 
        group by 1 
    ) abc 
on abc.product_key =p.id
 ) p


GROUP BY 1 , 2

)
select '@YDAY' ReportDate, CREATED_YDAY Val, concat('plugin_',Pgroup,'_',Pname,'_CREATED_YDAY') DataId from plugins_daily
UNION
select '@YDAY', ACTIVATED_YDAY, concat('plugin_',Pgroup,'_',Pname,'_ACTIVATED_YDAY') from plugins_daily
UNION
select '@YDAY', WAITING_YDAY, concat('plugin_',Pgroup,'_',Pname,'_WAITING_YDAY') from plugins_daily
UNION
select '@YDAY', case when pname in ('CARDCOM','MAX','MESHULAM','ISRACARD') then CNT_CLR_ACTIVE else CNT_ACTIVE end CNT_ACTIVE, concat('plugin_',Pgroup,'_',Pname,'_CNT_ACTIVE') from plugins_daily
UNION
select '@YDAY', REMOVED_YDAY, concat('plugin_',Pgroup,'_',Pname,'_REMOVED_YDAY') from plugins_daily
